name: 'Github Tag Bump'
description: 'Bump and push git tag on merge to master'
author: 'sumitkumar@sharechat.co'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
branding:
  icon: 'git-merge'
  color: 'purple'